---

- hosts: localhost
  connection: local
  vars:
    code_server_version: 3.4.1
    certbot_certs: 
      - domains:
          - {{ your_domain_name }}

  tasks:

    - name: Fetch Code Server Role
      git:
        repo: https://ro:Dff9yG2MNk3-dXBcA3Sp@pwslab.org/ansible/codeserver-playbook.git
        dest: /root/.ansible/roles/pwslab.codeserver
        version: master
        force: yes

    - name: Install Role NGINX
      local_action: command ansible-galaxy install -f geerlingguy.nginx 

    - name: Install Role CertBot
      local_action: command ansible-galaxy install -f geerlingguy.certbot 

    - pause:
          prompt: "Please Type Domain Name"
          echo: yes
      register: your_domain_name_result

    - set_fact:
            your_domain_name: "{{ your_domain_name_result.user_input }}"

    
    - name: Check if Nginx is already installed
      stat: path=/usr/sbin/nginx
      register: nginx_exists
    
    - name: Applying role Nginx
      command: mv ~/.ansible/roles/geerlingguy.nginx ~/.ansible/roles/pwslab.nginx
      when: not nginx_exists.stat.exists
      ignore_errors: yes

    - name: Applying role Certbot
      command: mv ~/.ansible/roles/geerlingguy.certbot ~/.ansible/roles/pwslab.certbot
      when: not nginx_exists.stat.exists
      ignore_errors: yes

    - name: Installing codeserver
      include_role:
        name: pwslab.codeserver
    
    - name: Installing NGINX
      include_role:
        name: pwslab.nginx
      when: not nginx_exists.stat.exists

    - name: Installing Certbot
      include_role:
        name: pwslab.certbot
      when: not nginx_exists.stat.exists


    